name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Make maven wrapper script executable for Order Manager
        run: chmod +x ./mvnw
      - name: Test
        run: ./mvnw -f pom.xml clean test
      - name: Build
        run: ./mvnw -f pom.xml package

      - name: Publish Test Reports
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: '**/target/surefire-reports/*.xml'